image: registry.gitlab.com/vrigzalejo/covid19-backend:latest

stages:
    - test

variables:
    FLASK_ENV: development

test:
    stage: test
    script:
        - cp .env.example .env
        - cd core
        - flask db upgrade
        - python manage.py seed
        - flake8
        - python -m pytest
