version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        FLASK: application
    ports:
      - 80:80
    depends_on:
      - application

  application:
    build: ./core
    command: gunicorn -c gunicorn_ini.py wsgi:app --reload
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000
