"""empty message

Revision ID: 6066c74ea74a
Revises: 
Create Date: 2020-04-10 20:32:50.563363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6066c74ea74a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_state', sa.String(length=128), nullable=True),
    sa.Column('country_region', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmed_global',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_region_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_region_id'], ['country_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmed_global')
    op.drop_table('country_regions')
    # ### end Alembic commands ###
