"""empty message

Revision ID: d7deea50d77d
Revises: 
Create Date: 2020-04-11 15:23:43.542790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7deea50d77d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_state', sa.String(length=128), nullable=True),
    sa.Column('country_region', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmed_global',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_region_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['country_region_id'], ['country_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deaths_global',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_region_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['country_region_id'], ['country_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovered_global',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_region_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['country_region_id'], ['country_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovered_global')
    op.drop_table('deaths_global')
    op.drop_table('confirmed_global')
    op.drop_table('country_regions')
    # ### end Alembic commands ###
